discover/urls.py
from django.urls import path 
from . import views

app_name = 'discover'
urlpatterns = [
    path('', views.index, name= 'index'),
    path('<int:publication_id>/detail/', views.detail, name='detail'),
    path('resultat/', views.resultat, name='resultat'),
    path('category/', views.category, name='category'),
    path('<int:category_id>/list_category/', views.list_category, name='list_category'),
    path('register/', views.register, name='register'),
    path('registered/', views.registered, name='registered'),
    path('login/', views.my_login, name='login'),
    path('logout/', views.my_logout, name='logout'),
    path('welcome/', views.welcome, name='welcome'),
    path('published/', views.published, name='published'),
]

singular/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('discover/', include('discover.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

discover/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User

# Create your models here.
class Users(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    avatar_user = models.ImageField(upload_to='Avatar', blank=True)
    
    def __str__(self):
        affiche = f"{self.user.last_name} {self.user.first_name}"
        return affiche

class Adress(models.Model):
    street_adress = models.CharField(max_length=100)
    city_adress = models.CharField(max_length=50)
    cp_adress = models.CharField(max_length=50)

    def __str__(self):
        affiche = f"{self.street_adress} {self.city_adress} {self.cp_adress}"
        return affiche

class Statut(models.Model):
    name_statut = models.CharField(max_length=50)

    def __str__(self):
        affiche = f"{self.name_statut}"
        return affiche

class Creator(models.Model):
    name_creator = models.CharField(max_length=50)
    firstname_creator = models.CharField(max_length=50)
    birthdate_creator = models.DateField("Date de naissance du createur")
    statut = models.ManyToManyField(Statut)
    avatar_creator = models.ImageField(upload_to='pictures_creator', blank=True)

    def __str__(self):
        affiche = f"{self.firstname_creator} {self.name_creator}"
        return affiche

class TypeLayout(models.Model):
    name_typeLayout = models.CharField(max_length=50)

    def __str__(self):
        affiche = f"{self.name_typeLayout}"
        return affiche

class Layout(models.Model):
    name_layout = models.CharField(max_length=50)
    number_layout = models.IntegerField(default=0)
    type_layout = models.ForeignKey(TypeLayout, on_delete=models.CASCADE)

    def __str__(self):
        affiche = f"{self.Layout}"
        return affiche

class SubCategory(models.Model):
    name_subCategory = models.CharField(max_length=50)

    def __str__(self):
        affiche = f"{self.name_subCategory}"
        return affiche

class Category(models.Model):
    name_category = models.CharField(max_length=50)
    avatar_category = models.ImageField(upload_to='pictures_category', blank=True)
    subcategory = models.ManyToManyField(SubCategory)

    def __str__(self):
        affiche = f"{self.name_category}"
        return affiche

class Publication(models.Model):
    name_publication = models.CharField(max_length=50)
    date_publication = models.DateField("Date de publication")
    description_publication = models.TextField(null=True, blank=True)
    pictures_publication =models.avatar_user = models.ImageField(upload_to='Pictures_publication', blank=True)
    users = models.ManyToManyField(User, through='Favorite', blank=True)
    adress = models.ForeignKey(Adress, on_delete=models.CASCADE)
    creator = models.ForeignKey(Creator, on_delete=models.CASCADE, null=True, blank=True)
    category = models.ManyToManyField(SubCategory)
    layout = models.ManyToManyField(Layout, blank=True)

#    def early_publish(self):
#       now = timezone.now()
#        return now - datetime.timedelta(days=7) <= self.date_publication <= now

    def __str__(self):
        affiche = f"{self.name_publication}"
        return affiche

class Favorite(models.Model):
    publication = models.ForeignKey(Publication, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    favorite = models.BooleanField(default=False)

class Rate(models.Model):
    comments = models.TextField()
    choice = (
            (1, 'Mauvais'),
            (2, 'Faible'),
            (3, 'Moyen'),
            (4, 'Intéressant'),
            (5, 'Incroyable !'),
    ) 
    note = models.IntegerField(choices=choice, default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    publication = models.ForeignKey(Publication, on_delete=models.CASCADE)

    def __str__(self):
        affiche = f"{self.note} {self.comments}"
        return affiche

discover/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login , logout
from . models import Publication, Users, Adress, Statut, Creator, Layout, TypeLayout, SubCategory, Category, Favorite, Rate

# Create your views here.

# PLACES 
def index(request):
    last_publish = Publication.objects.order_by('id')
    category =  Category.objects.all()
    subcategory =  SubCategory.objects.all()
    context = {
        'publish_list': last_publish,
        'category': category ,
        'subcategory': subcategory
    }
    return render(request, 'discover/index.html', context)

def detail(request, publication_id):
    detail = get_object_or_404(Publication, pk=publication_id)
    context = {'detail': detail}
    return render(request, 'discover/detail.html', context)

def resultat(request):
    context = {}
    publication_name = []

    if request.method == "POST":
        search_input = request.POST['search_input'].lower()
        words = search_input.split(" ")
        
        #Search by name publication 
        for word in words:
            publication = Publication.objects.filter(name_publication__contains=word)
            for pub in publication:
                publication_name.append(pub)
                
        #Search by date publication
        # publication_date = Publication.objects.filter(date_publication__contains=word)

        #Search by adress publication 
        # publication_adress = Publication.objects.filter(adress__contains=search_input)

        #Search by creator
        # publication_creator = Publication.objects.filter(creator__contains=search_input)

        #Search by layout 
        # publication_layout = Publication.objects.filter(layout__name_layout__contains=search_input)

        # Search by category
        # publication_category = Publication.objects.filter(category__name_category__contains=search_input)

        context = {
            'search_input': search_input,
            'publication' :publication,
            # 'publication_date': publication_date,
            # 'publication_creator': publication_creator,
            # 'publication_adress': publication_adress,
            # 'publication_creator': publication_creator,
            # 'publication_layout': publication_layout,
            # 'publication_category': publication_category,
        }

        return render(request, 'discover/resultat.html', context)
    else:
        return render(request, 'discover/resultat.html', context)


# CATEGORY

def category(request):
    category = Category.objects.order_by('id')
    subcategory = SubCategory.objects.order_by('id')
    context = {
        'category': category,
        'subcategory': subcategory,
    }
    return render(request, 'discover/category/category.html', context)   

# def list_category(request, category_id):
#     category1 = get_object_or_404(Category, pk=category_id)
#     list_publication = Publication.objects.filter(category_id=category_id).values()
#     context = {
#         'category':category1,
#         'list_publication': list_publication,
#     }
#     return render(request, 'discover/category/list_category.html', context)

def list_category(request, category_id):
    categ = get_object_or_404(Category, pk=category_id)
    liste_publication = Publication.objects.filter(category=category_id).values('id', 'name_publication', 'date_publication', 'creator', 'category', 'pictures_publication')
    for pub in liste_publication:
        ca = get_object_or_404(Category, pk=pub['category'])
        sc = get_object_or_404(SubCategory, pk=pub['subcategory'])
        c1 = get_object_or_404(Creator, pk=pub['creator'])

        pub['category']={
            'id':ca.id, 
            'name_category':ca.name_category, 
            'avatar_category':ca.avatar_category
            }

        pub['subcategory']={
            'id':sc.id, 
            'name_subCategory':sc.name_subCategory
            }

        pub['creator']={
            'id':c1.id, 
            'name_creator':c1.name_creator, 
            'firstname_creator':c1.firstname_creator, 
            'birthdate_creator':c1.birthdate_creator, 
            'avatar_creator':c1.avatar_creator
            }

    context = {
        'categ':categ, 
        'liste_publication':liste_publication}
    return render(request, 'discover/category/list_category.html', context)

# ACCOUNT

def my_login(request):
    return render(request, 'discover/account/login.html')

def welcome(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    context = {'user':user}
    if user is not None :
        login(request, user)
        return render(request, 'discover/account/welcome.html', context)
    else:
        return render(request, 'discover/account/error_log.html')

def my_logout(request):
    logout(request)
    return render(request, 'discover/account/logout.html')

def register(request):
    return render(request, 'discover/account/register.html')

def registered(request):
    name = request.POST['user_name']
    firstname = request.POST['user_firstname']
    pwd = request.POST['user_pwd']
    email = request.POST['user_email']
    avatar = request.POST['user_avatar']
    username = firstname[0].lower() + "." + name.lower()
    user = User.objects.create_user(username, email, pwd)
    utilisateur = Users(user=user)
    user.last_name = name
    user.first_name = firstname
    utilisateur.avatar_user = avatar
    user.save()
    utilisateur.save()
    context = {'user':user}
    return render(request, 'discover/account/registered.html', context)
        # return render(request, 'discover/error_log_inscription.html')

# PUBLICATION 

def published(request):
    # lieu = request.POST['lieu']
    # creator = request.POST['creator']
    # category = request.POST['category']
    # avatar_publication = request.POST['avatar_publication']
    # publication = Publication.objects.create_publication(name_publication, )
    return render(request, 'discover/account/published.html')

discover/templates/discover/account/error_log.html
{% extends 'discover/index.html' %}
{% load static %}

{% block title%}
{% endblock %}
{% block content%}
<div class="containerInfo">
    <h1 class="p_detail">Nom d'utilisateur ou mot de passe incorrect </h1>
    <a class="fancy-btn" href="{% url 'discover:login' %}">Connexion</a>
    <a class="fancy-btn" href="{% url 'discover:index' %}">Revenir sur l'accueil</a>
</div>
{% endblock %}

discover/templates/discover/account/error_log_inscription.html
{% extends 'discover/index.html' %}
{% load static %}

{% block title%}
{% endblock %}
{% block content%}
<div class="containerInfo">
    <h1 class="p_detail">Utilisateur déjà connu </h1>
    <a class="fancy-btn" href="{% url 'discover:register' %}">Inscription</a>
    <a class="fancy-btn" href="{% url 'discover:index' %}">Revenir sur l'accueil</a>
</div>
{% endblock %}

discover/templates/discover/account/login.html
{% extends 'discover/index.html' %}
{% load static %}


{% block title %}
{% endblock %}

{% block content %}

    <div class="container_login">
        <div class="card_login">
            <div class="card-image">
                <h1 class="card-heading title2">Identifiez-vous</h1>
            </div>
            <a class="a_detail" href="{% url 'discover:register' %}">Pas de compte ? Inscrivez-vous !</a>
            <form class="card-form" id="login" method="post" action="{% url 'discover:welcome' %}">
                {% csrf_token %}
                <div class="input_login">
                    <input type="text" class="input-field" id="username" name="username" required />
                    <label class="input-label">Pseudo</label>
                </div>
                <div class="input_login">
                    <input type="password" class="input-field" id="password" name="password" required />
                    <label class="input-label">Mot de passe</label>
                </div>
                <div class="action_login">  
                    <input class="bouton_login" type="submit" value="Connexion">
                    <input type="hidden" name="{{next}}">
                </div>
            </form>
        </div>
    </div>
{% endblock %}

discover/templates/discover/account/logout.html
{% extends 'discover/index.html' %}
{% load static %}

{% block title %}
{% endblock %}

    {% block content %}
    <div class="containerInfo">
        <h3 class="p_detail">Merci de votre visite, à bientôt</h3>
        <a class="fancy-btn" href="{% url 'discover:index' %}">Accueil</a>
    </div>
    {% endblock %}

discover/templates/discover/account/published.html
{% extends "discover/index.html" %}
{% load static %}


{% block content %}

<div class="container_pub">
    <div class="card_pub">
        <div class="card-image">
            <h1 class="card-heading title2">Publier</h1>
        </div>
        <form class="card-form" id="published" method="post" action="{% url 'discover:published' %}">
            {% csrf_token %}
            <div class="input_pub">
                <input type="text" class="input-field" id="lieu" name="lieu" required/>
                <label class="input-label" for="lieu">Nom du lieu</label>
            </div>
            <div class="input_pub">
                <input type="text" class="input-field" id="creator" name="creator" required/>
                <label class="input-label" for="creator">Créateur</label>
            </div>
            <div class="input_pub">
                <input type="text" class="input-field" id="category" name="category" required/>
                <label class="input-label" for="category">Catégories</label>
            </div>

            <div class="input_pub">
                <input type="text" class="input-field" id="description" name="description" required/>
                <label class="input-label" for="category">Description</label>
            </div>

            <div class="input_pub">
                <input type="file" class="input-field" id="avatar_publication" name="avatar_publication"/>
                <label class="input-label" for="avatar_publication">Photo</label>
            </div>
            <div class="action_pub">
                <input class="bouton_pub" type="submit" value="publier">
            </div>
        </form>
    </div>
</div>
{% endblock %}

discover/templates/discover/account/register.html
{% extends "discover/index.html" %}
{% load static %}


{% block title %}
{% endblock %}

{% block content %}

<div class="container_login">
    <div class="card_login">
        <div class="card-image">
            <h1 class="card-heading title2">Inscription</h1>
        </div>
        <a class="a_detail" href="{% url 'discover:login' %}">Déjà un compte ? Connectez-vous !</a>
        <form class="card-form" id="register" method="post" action="{% url 'discover:registered' %}">
            {% csrf_token %}
            <div class="input_login">
                <input type="text" class="input-field" id="user_name" name="user_name" required/>
                <label class="input-label" for="user_name">Nom</label>
            </div>
            <div class="input_login">
                <input type="text" class="input-field" id="user_firstname" name="user_firstname" required/>
                <label class="input-label" for="user_firstname">Prénom</label>
            </div>
            <div class="input_login">
                <input type="text" class="input-field" id="user_email" name="user_email" required/>
                <label class="input-label" for="user_email">Email</label>
            </div>
            <div class="input_login">
                <input type="password" class="input-field" id="user_pwd" name="user_pwd" required/>
                <label class="input-label" for="user_pwd">Mot de passe</label>
            </div>
            <div class="input_login">
                <input type="file" class="input-field" id="user_avatar" name="user_avatar"/>
                <label class="input-label" for="user_avatar">Photo de profil</label>
            </div>
            <div class="action_login">
                <input class="bouton_login" type="submit" value="Enregistrer">
            </div>
        </form>
    </div>
</div>
{% endblock %}

discover/templates/discover/account/registered.html
{% extends 'discover/index.html' %}
{% load static %}


{% block title %}
{% endblock %}
    {% block content %}
    <div class="containerInfo">
        <h1 class="title4">Bienvenue</h1>
        <p class="p_detail">
            Votre nom d'utilisateur est : {{user.username}}
        </p>
        <a class="fancy-btn" href="{% url 'discover:login' %}">Login</a>
    </div>
    {% endblock %}

discover/templates/discover/account/welcome.html
{% extends "discover/index.html" %}
{% load static %}


{% block title %}
{% endblock %}

{% block content %}

<div class="containerInfo">
    {% if user.avatar_user %}
        <img src="{{ user.avatar_user.url }}">
    {% endif %} 
    <h1 class="title4">Bienvenue {{last_name}} {{first_name}}!</h1>
    <p class="p_detail">Connexion réussi !</p>
    <a class="fancy-btn" href="{% url 'discover:index' %}">Page d'accueil</a>
</div>

{% endblock %}