discover/urls.py
from django.urls import path 
from . import views

app_name = 'discover'
urlpatterns = [
    path('', views.index, name= 'index'),
    path('<int:publication_id>/detail/', views.detail, name='detail'),
    path('resultat/', views.resultat, name='resultat'),
    path('category/', views.category, name='category'),
    path('<int:category_id>/list_category/', views.list_category, name='list_category'),
    path('register/', views.register, name='register'),
    path('registered/', views.registered, name='registered'),
    path('login/', views.my_login, name='login'),
    path('logout/', views.my_logout, name='logout'),
    path('welcome/', views.welcome, name='welcome'),
    path('published/', views.published, name='published'),
]

singular/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('discover/', include('discover.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

discover/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User

# Create your models here.
class Users(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    avatar_user = models.ImageField(upload_to='Avatar', blank=True)
    
    def __str__(self):
        affiche = f"{self.user.last_name} {self.user.first_name}"
        return affiche

class Adress(models.Model):
    street_adress = models.CharField(max_length=100)
    city_adress = models.CharField(max_length=50)
    cp_adress = models.CharField(max_length=50)

    def __str__(self):
        affiche = f"{self.street_adress} {self.city_adress} {self.cp_adress}"
        return affiche

class Statut(models.Model):
    name_statut = models.CharField(max_length=50)

    def __str__(self):
        affiche = f"{self.name_statut}"
        return affiche

class Creator(models.Model):
    name_creator = models.CharField(max_length=50)
    firstname_creator = models.CharField(max_length=50)
    birthdate_creator = models.DateField("Date de naissance du createur")
    statut = models.ManyToManyField(Statut)
    avatar_creator = models.ImageField(upload_to='pictures_creator', blank=True)

    def __str__(self):
        affiche = f"{self.firstname_creator} {self.name_creator}"
        return affiche

class TypeLayout(models.Model):
    name_typeLayout = models.CharField(max_length=50)

    def __str__(self):
        affiche = f"{self.name_typeLayout}"
        return affiche

class Layout(models.Model):
    name_layout = models.CharField(max_length=50)
    number_layout = models.IntegerField(default=0)
    type_layout = models.ForeignKey(TypeLayout, on_delete=models.CASCADE)

    def __str__(self):
        affiche = f"{self.Layout}"
        return affiche

class SubCategory(models.Model):
    name_subCategory = models.CharField(max_length=50)

    def __str__(self):
        affiche = f"{self.name_subCategory}"
        return affiche

class Category(models.Model):
    name_category = models.CharField(max_length=50)
    avatar_category = models.ImageField(upload_to='pictures_category', blank=True)
    subcategory = models.ManyToManyField(SubCategory)

    def __str__(self):
        affiche = f"{self.name_category}"
        return affiche

class Publication(models.Model):
    name_publication = models.CharField(max_length=50)
    date_publication = models.DateField("Date de publication")
    description_publication = models.TextField(null=True, blank=True)
    pictures_publication =models.avatar_user = models.ImageField(upload_to='Pictures_publication', blank=True)
    users = models.ManyToManyField(User, through='Favorite', blank=True)
    adress = models.ForeignKey(Adress, on_delete=models.CASCADE)
    creator = models.ForeignKey(Creator, on_delete=models.CASCADE, null=True, blank=True)
    category = models.ManyToManyField(SubCategory)
    layout = models.ManyToManyField(Layout, blank=True)

#    def early_publish(self):
#       now = timezone.now()
#        return now - datetime.timedelta(days=7) <= self.date_publication <= now

    def __str__(self):
        affiche = f"{self.name_publication}"
        return affiche

class Favorite(models.Model):
    publication = models.ForeignKey(Publication, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    favorite = models.BooleanField(default=False)

class Rate(models.Model):
    comments = models.TextField()
    choice = (
            (1, 'Mauvais'),
            (2, 'Faible'),
            (3, 'Moyen'),
            (4, 'Intéressant'),
            (5, 'Incroyable !'),
    ) 
    note = models.IntegerField(choices=choice, default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    publication = models.ForeignKey(Publication, on_delete=models.CASCADE)

    def __str__(self):
        affiche = f"{self.note} {self.comments}"
        return affiche

discover/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login , logout
from . models import Publication, Users, Adress, Statut, Creator, Layout, TypeLayout, SubCategory, Category, Favorite, Rate

# Create your views here.

# PLACES 
def index(request):
    last_publish = Publication.objects.order_by('id')
    category =  Category.objects.all()
    subcategory =  SubCategory.objects.all()
    context = {
        'publish_list': last_publish,
        'category': category ,
        'subcategory': subcategory
    }
    return render(request, 'discover/index.html', context)

def detail(request, publication_id):
    detail = get_object_or_404(Publication, pk=publication_id)
    context = {'detail': detail}
    return render(request, 'discover/detail.html', context)

def resultat(request):
    context = {}
    publication_name = []

    if request.method == "POST":
        search_input = request.POST['search_input'].lower()
        words = search_input.split(" ")
        
        #Search by name publication 
        for word in words:
            publication = Publication.objects.filter(name_publication__contains=word)
            for pub in publication:
                publication_name.append(pub)
                
        #Search by date publication
        # publication_date = Publication.objects.filter(date_publication__contains=word)

        #Search by adress publication 
        # publication_adress = Publication.objects.filter(adress__contains=search_input)

        #Search by creator
        # publication_creator = Publication.objects.filter(creator__contains=search_input)

        #Search by layout 
        # publication_layout = Publication.objects.filter(layout__name_layout__contains=search_input)

        # Search by category
        # publication_category = Publication.objects.filter(category__name_category__contains=search_input)

        context = {
            'search_input': search_input,
            'publication' :publication,
            # 'publication_date': publication_date,
            # 'publication_creator': publication_creator,
            # 'publication_adress': publication_adress,
            # 'publication_creator': publication_creator,
            # 'publication_layout': publication_layout,
            # 'publication_category': publication_category,
        }

        return render(request, 'discover/resultat.html', context)
    else:
        return render(request, 'discover/resultat.html', context)


# CATEGORY

def category(request):
    category = Category.objects.order_by('id')
    subcategory = SubCategory.objects.order_by('id')
    context = {
        'category': category,
        'subcategory': subcategory,
    }
    return render(request, 'discover/category/category.html', context)   

# def list_category(request, category_id):
#     category1 = get_object_or_404(Category, pk=category_id)
#     list_publication = Publication.objects.filter(category_id=category_id).values()
#     context = {
#         'category':category1,
#         'list_publication': list_publication,
#     }
#     return render(request, 'discover/category/list_category.html', context)

def list_category(request, category_id):
    categ = get_object_or_404(Category, pk=category_id)
    liste_publication = Publication.objects.filter(category=category_id).values('id', 'name_publication', 'date_publication', 'creator', 'category', 'pictures_publication')
    for pub in liste_publication:
        ca = get_object_or_404(Category, pk=pub['category'])
        sc = get_object_or_404(SubCategory, pk=pub['subcategory'])
        c1 = get_object_or_404(Creator, pk=pub['creator'])

        pub['category']={
            'id':ca.id, 
            'name_category':ca.name_category, 
            'avatar_category':ca.avatar_category
            }

        pub['subcategory']={
            'id':sc.id, 
            'name_subCategory':sc.name_subCategory
            }

        pub['creator']={
            'id':c1.id, 
            'name_creator':c1.name_creator, 
            'firstname_creator':c1.firstname_creator, 
            'birthdate_creator':c1.birthdate_creator, 
            'avatar_creator':c1.avatar_creator
            }

    context = {
        'categ':categ, 
        'liste_publication':liste_publication}
    return render(request, 'discover/category/list_category.html', context)

# ACCOUNT

def my_login(request):
    return render(request, 'discover/account/login.html')

def welcome(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    context = {'user':user}
    if user is not None :
        login(request, user)
        return render(request, 'discover/account/welcome.html', context)
    else:
        return render(request, 'discover/account/error_log.html')

def my_logout(request):
    logout(request)
    return render(request, 'discover/account/logout.html')

def register(request):
    return render(request, 'discover/account/register.html')

def registered(request):
    name = request.POST['user_name']
    firstname = request.POST['user_firstname']
    pwd = request.POST['user_pwd']
    email = request.POST['user_email']
    avatar = request.POST['user_avatar']
    username = firstname[0].lower() + "." + name.lower()
    user = User.objects.create_user(username, email, pwd)
    utilisateur = Users(user=user)
    user.last_name = name
    user.first_name = firstname
    utilisateur.avatar_user = avatar
    user.save()
    utilisateur.save()
    context = {'user':user}
    return render(request, 'discover/account/registered.html', context)
        # return render(request, 'discover/error_log_inscription.html')

# PUBLICATION 

def published(request):
    # lieu = request.POST['lieu']
    # creator = request.POST['creator']
    # category = request.POST['category']
    # avatar_publication = request.POST['avatar_publication']
    # publication = Publication.objects.create_publication(name_publication, )
    return render(request, 'discover/account/published.html')

discover/templates/discover/detail.html
{% extends 'discover/index.html' %}
{% load static %}
{% load i18n %}


{% block content %}
        <div>
            <h1>{{ detail.name_publication }}</h1>
            {% for category in detail.subcategory.all %}
                {% for categ in category.category.all %}
                    <p><strong>{{ categ.name_category }}</strong> {{ category.name_subCategory }}</p>
                {% endfor%}
            {% endfor %}
            {% language 'fr' %}
            <p> {{ detail.date_publication|date:'d F Y' }}</p>
            {% endlanguage %}
            {% if detail.pictures_publication %}
                <img src="{{ detail.pictures_publication.url }}">
            {% endif %} 
            {{ detail.adress }}
            <p> Description :<br> {{ detail.description_publication }}</p>
            {{ detail.creator }}
            {% for create in detail.creator.all %}
                <p>{{ create.name_creator }}</p>
                <p>{{ create.firstname_creator }}</p>
                <p>{{ create.birthdate_creator }}</p>
                <p>{{ create.statut }}</p>
            {% endfor %}
        </div>
{% endblock %}

discover/templates/discover/index.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/8e8d5e63b3.js"></script><!--Icone -->
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet"> <!-- AOS Librairy-->
    <link rel="stylesheet" type="text/css" href="{% static 'discover/CSS/style.css' %}"> <!--CSS-->
    <title>Singular &mdash; Accueil</title>
</head>
<body>
    <!-- lOGO -->
    <div id="navbar">
        <div class="logo">
            <a href="{% url 'discover:index' %}">
                <h1 data-aos="fade-right" data-aos-duration="2000">Singular</h1>
            </a>
        </div>

        <!-- NAVBAR -->
        <div data-aos="fade-left" data-aos-duration="2000"  class="nav">
            <a href="{% url 'discover:index' %}">Accueil</a>
            <a href="{% url 'discover:category'%}">Catégories</a>
        </div>

        <!-- USER NAVBAR -->
        <div class="user_navbar">
            <ul>    
                {% if not request.user.is_authenticated %}
                    <li><a href="{% url 'discover:login' %}">Connexion</a></li>
                    <li><a href="{% url 'discover:register' %}">Inscription</a></li>
                {% else %}
                    <li><a href="{% url 'discover:published' %}">Publier</a></li>
                    <li><a href="#">Profil</a></li>
                    <li><a href="{% url 'discover:logout' %}">Déconnexion</a></li>
                {% endif %}  
            </ul>
        </div>
    </div>

    <!-- SEARCH SECTION -->
    <div class="searchbar">
        <h1 class="titre_search" data-aos="zoom-out" data-aos-duration="1500" data-aos-easing="ease-in-out">Singular</h1>
        <h2 class="titre_search2" data-aos="zoom-out" data-aos-duration="1500">A la recherche de singularité ?</h2>
        <form method="POST" action="{% url 'discover:resultat' %}">
            {% csrf_token %}
            <input type="search" id="search_input" name="search_input" placeholder="Recherche">
            <button type="submit" id="search_button">
                <i class="fa fa-search"></i>
            </button>
        </form>
    </div>

    {% block content %}

    <!-- CATEGORY SECTION -->
    <section class="category_section">
        <div class="head_category">
            <p class="top_title" data-aos="fade-left" >Notre</p>
            <h2 data-aos="fade-right">Sélection</h2>
            <p class="top_title" data-aos="fade-left">Découvrez nos catégories disponibles</p>
        </div>

        <ul class="cards" data-aos="fade">
            {% for categ in category %}
                <li>
                    <a href="" class="card">
                        <img src={{ categ.avatar_category.url }} class="card__image" alt="" />
                        <div class="card__overlay">
                            <div class="card__header">
                                <div class="card__header-text">
                                    <h3 class="card__title">{{ categ.name_category }}</h3>            
                                </div>
                            </div>
                            {% for subcateg in categ.subcategory.all %}
                                <p class="card__description">{{ subcateg.name_subCategory }}</p>
                            {% endfor %}
                        </div>
                    </a>      
                </li>
            {% endfor %}
        </ul>
    </section>

    <!-- LAST PUBLICATION -->
    {% if publish_list %}
            <div class="container_box">
                <div class="head_category">
                    <p data-aos= "fade-left" class="top_title">Pour vous</p>
                    <h2 data-aos= "fade-right">Nos découvertes</h2>
                    <p  data-aos= "fade-left" class="top_title">Les dernières publications du jour</p>
                </div>
                
                {% for publication in publish_list %}    
                    <div data-aos="fade-top" class="card">
                        <div>
                            <h1>{{ publication.name_publication }}</h1>
                            <div><img src="{{ publication.pictures_publication.url }}"/>
                                <h2>{{ publication.creator }}</h2>
                            </div>
                            <div class="separator"></div>
                            <p>{{ publication.description_publication }}</p>
                        </div>
                        <div>
                            {% language 'fr' %}
                            <h5>{{ publication.date_publication|date:'d F Y' }}</h5>
                            {% endlanguage %}
                        </div>
                        <button><a href="{% url 'discover:detail' publication.id %}">Détails</a></button>
                    </div>
            {% endfor %}
        {% else %}
            <p>Pas de publications récentes disponibles</p>
        </div>
        {% endif %}

    {% endblock %}

    <!-- SCRIPT SECTION -->
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script src="{% static 'discover/JS/animate.js' %}"></script>
    <script>
        AOS.init();
    </script>
    <!-- END SCRIPT -->
</body>
</html>

discover/templates/discover/resultat.html
{% extends 'discover/index.html' %}
{% load static %}
{% load i18n %}

{% block content %}
<h1 data-aos="fade-right" data-aos-duration="2000" class="titreH1">Résultats des recherches</h1>
{% if search_input %}
    <h1 class="titre_resultat">Pour "{{ search_input }}"</h1>
    <div class="container">

        <!-- Result for publication name -->
        {% for result in publication %}
            <div data-aos="fade" data-aos-duration="2000"  class="main">
                <ul>
                    <li>
                        <div>
                            <h3>
                                <span>{{ result.name_publication }}</span>
                                <span><b>{{ result.creator }}</b></span>
                            </h3>
                            <p>
                                {% language 'fr' %}
                                <b>Date de publication</b> : {{ result.date_publication|date:'d F Y' }}
                                {% endlanguage %}
                            </p>

                            <p>
                                <b>Catégorie</b> : {{ result.category }}
                            </p>
                            <p>
                                <b>Aménagements</b> : {{ result.layout }}
                            </p>
                            <button><a href="{% url 'discover:detail' result.id %}">Détails</a></button>
                        </div>
                    </li>
                </ul> 
            </div> <!-- end main -->
        {% endfor %}

        <!-- Result for publication date -->
        {% for result in publication_date %}
            <div data-aos="fade" data-aos-duration="2000"  class="main">
                <ul>
                    <li>
                        <div>
                            <h3>
                                <span>{{ result.name_publication }}</span>
                                <span><b>{{ result.creator }}</b></span>
                            </h3>
                            <p>
                                {% language 'fr' %}
                                <b>Date de publication</b> : {{ result.date_publication|date:'d F Y' }}
                                {% endlanguage %}
                            </p>

                            <p>
                                <b>Catégorie</b> : {{ result.category }}
                            </p>
                            <p>
                                <b>Aménagements</b> : {{ result.layout }}
                            </p>
                            <button><a href="{% url 'discover:detail' result.id %}">Détails</a></button>
                        </div>
                    </li>
                </ul> 
            </div> <!-- end main -->
        {% endfor %}
{% endif %}
{% endblock %}